/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '30/08/16 8:32 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 30/08/16 8:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
